.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "INDEXER" "" "June 2021" ""
.SH "NAME"
\fBindexer\fR \- basic program to index files (for websites or anything)
.SH "SYNOPSIS"
indexer [\-\-css] [\-T] [\-\-help] files
.P
e\.g\.
.P
indexer \-\-css style\.css \-T html *\.txt > index\.html
.SH "ARGUMENTS"
\-\-css file\.css	\-	add css stylesheet when using \-T html
.P
\-T md / html	\-	specify output format
.P
\-\-help		\-	show help
