.TH "INDEXER" "1"
.SH "NAME"
\fBindexer\fR \- basic program to index files (for websites or anything)
.SH "SYNOPSIS"
indexer [arguments] files
.P
e\.g\.
.P
indexer \-\-css style\.css \-T html \-d "[dir] " \-f "[file] " *\.txt > index\.html
.SH "ARGUMENTS"
	\-\-css file			\-	adds a single css file
.P
	\-T					\-	sets output format. supported: md, html
.P
	\-d / \-\-dir-emoji str	\-	sets an emoji/str for directories
.P
	\-f / \-\-file-emoji str	\-	sets an emoji/str for files
.P
	\-\-help				\-	shows help end exits
.P
